"""remove claim_simulation_id from claim_procedure_details

Revision ID: 4817ac29496c
Revises: a1713899816b
Create Date: 2025-10-23 16:42:52.524932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4817ac29496c'
down_revision: Union[str, None] = 'a1713899816b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('claim_procedure_details_claim_simulation_id_fkey', 'claim_procedure_details', type_='foreignkey')
    op.drop_column('claim_procedure_details', 'claim_simulation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_procedure_details', sa.Column('claim_simulation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('claim_procedure_details_claim_simulation_id_fkey', 'claim_procedure_details', 'claim_simulations', ['claim_simulation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
