"""add created_at, is_deleted, is_dummy to claim_logs

Revision ID: 6d12fddcf24b
Revises: 5db13cf46f42
Create Date: 2025-11-03 11:57:32.867959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d12fddcf24b'
down_revision: Union[str, None] = '5db13cf46f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_logs', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_logs', 'created_at')
    # ### end Alembic commands ###