"""drop bab_pasal from claim_regulation_details

Revision ID: 79524eb7ddb5
Revises: 5d43427dcd21
Create Date: 2025-11-05 13:34:30.965956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79524eb7ddb5'
down_revision: Union[str, None] = '5d43427dcd21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_regulation_details', 'bab_pasal')
    # ### end Alembic commands ###


def downgrade():
    op.add_column('claim_regulation_details', sa.Column('bab_pasal', sa.String(), nullable=True))