"""add is_deleted and is_dummy flag

Revision ID: 7a5787bc54e0
Revises: d218e18f9763
Create Date: 2025-09-07 21:29:47.514581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5787bc54e0'
down_revision: Union[str, None] = 'd218e18f9763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_ai_recommendations', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('claim_ai_recommendations', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    op.add_column('claim_ai_recommendations_summary', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('claim_ai_recommendations_summary', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    op.add_column('claim_logs', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('claim_logs', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    op.add_column('claim_procedures', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('claim_procedures', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    op.add_column('claim_tariffs', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('claim_tariffs', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    op.add_column('hospitals', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('hospitals', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    op.add_column('medical_record_logs', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('medical_record_logs', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    op.add_column('medical_records', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('medical_records', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    op.add_column('visits', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('visits', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'is_dummy')
    op.drop_column('visits', 'is_deleted')
    op.drop_column('users', 'is_dummy')
    op.drop_column('users', 'is_deleted')
    op.drop_column('patients', 'is_dummy')
    op.drop_column('patients', 'is_deleted')
    op.drop_column('medical_records', 'is_dummy')
    op.drop_column('medical_records', 'is_deleted')
    op.drop_column('medical_record_logs', 'is_dummy')
    op.drop_column('medical_record_logs', 'is_deleted')
    op.drop_column('hospitals', 'is_dummy')
    op.drop_column('hospitals', 'is_deleted')
    op.drop_column('claim_tariffs', 'is_dummy')
    op.drop_column('claim_tariffs', 'is_deleted')
    op.drop_column('claim_procedures', 'is_dummy')
    op.drop_column('claim_procedures', 'is_deleted')
    op.drop_column('claim_logs', 'is_dummy')
    op.drop_column('claim_logs', 'is_deleted')
    op.drop_column('claim_diagnoses', 'is_dummy')
    op.drop_column('claim_diagnoses', 'is_deleted')
    op.drop_column('claim_ai_recommendations_summary', 'is_dummy')
    op.drop_column('claim_ai_recommendations_summary', 'is_deleted')
    op.drop_column('claim_ai_recommendations', 'is_dummy')
    op.drop_column('claim_ai_recommendations', 'is_deleted')
    # ### end Alembic commands ###
