"""add diagnosis_dictionary and procedure_dictionary tables

Revision ID: 7c1713f669ac
Revises: 0ead712326bc
Create Date: 2025-11-11 16:31:47.148914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = '7c1713f669ac'
down_revision: Union[str, None] = '0ead712326bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diagnosis_dictionary",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("keyword", sa.String(length=255), unique=True, nullable=False),
        sa.Column("icd10_id", sa.Integer(), sa.ForeignKey("icd10.id", ondelete="CASCADE")),
        sa.Column("method", sa.String(length=50), server_default="manual"),
        sa.Column("created_at", sa.DateTime(), server_default=text("now()")),
    )

    # === Procedure Dictionary Table ===
    op.create_table(
        "procedure_dictionary",
        sa.Column("id", sa.Integer(), primary_key=True, index=True),
        sa.Column("keyword", sa.String(length=255), unique=True, nullable=False),
        sa.Column("icd9_id", sa.Integer(), sa.ForeignKey("icd9.id", ondelete="CASCADE")),
        sa.Column("method", sa.String(length=50), server_default="manual"),
        sa.Column("created_at", sa.DateTime(), server_default=text("now()")),
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    op.drop_table("procedure_dictionary")
    op.drop_table("diagnosis_dictionary")