"""add is_dummy to claim_visit_links

Revision ID: 98015e9146f7
Revises: 6d12fddcf24b
Create Date: 2025-11-03 12:03:13.688642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98015e9146f7'
down_revision: Union[str, None] = '6d12fddcf24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_visit_links', sa.Column('is_dummy', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_visit_links', 'is_dummy')
    # ### end Alembic commands ###