"""add entry_field to claim_regulation_details

Revision ID: b2b26d6e262a
Revises: d22bc6652b7d
Create Date: 2025-10-21 14:21:26.186855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2b26d6e262a'
down_revision: Union[str, None] = 'd22bc6652b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_regulation_details', sa.Column('entry_field', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_regulation_details', 'entry_field')
    # ### end Alembic commands ###
