"""add struktur_icd10 to claim_diagnoses

Revision ID: c6308307e5ae
Revises: c139a2b8880d
Create Date: 2025-09-16 09:20:54.264338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6308307e5ae'
down_revision: Union[str, None] = 'c139a2b8880d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_ai_recommendations', 'regulation_refs')
    op.add_column('claim_diagnoses', sa.Column('struktur_icd10', sa.Text(), nullable=True))
    op.add_column('claim_simulations', sa.Column('stage', sa.String(), nullable=False))
    op.add_column('claim_simulations', sa.Column('tindakan_utama_id', sa.Integer(), nullable=True))
    op.add_column('claim_simulations', sa.Column('tindakan_sekunder_id', sa.Integer(), nullable=True))
    op.alter_column('claim_simulations', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_claim_simulations_id'), 'claim_simulations', ['id'], unique=False)
    op.drop_constraint('claim_simulations_procedure_utama_id_fkey', 'claim_simulations', type_='foreignkey')
    op.drop_constraint('claim_simulations_procedure_sekunder_id_fkey', 'claim_simulations', type_='foreignkey')
    op.create_foreign_key(None, 'claim_simulations', 'claim_procedures', ['tindakan_sekunder_id'], ['id'])
    op.create_foreign_key(None, 'claim_simulations', 'claim_procedures', ['tindakan_utama_id'], ['id'])
    op.drop_column('claim_simulations', 'procedure_sekunder_id')
    op.drop_column('claim_simulations', 'procedure_utama_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_simulations', sa.Column('procedure_utama_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('claim_simulations', sa.Column('procedure_sekunder_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'claim_simulations', type_='foreignkey')
    op.drop_constraint(None, 'claim_simulations', type_='foreignkey')
    op.create_foreign_key('claim_simulations_procedure_sekunder_id_fkey', 'claim_simulations', 'claim_procedures', ['procedure_sekunder_id'], ['id'])
    op.create_foreign_key('claim_simulations_procedure_utama_id_fkey', 'claim_simulations', 'claim_procedures', ['procedure_utama_id'], ['id'])
    op.drop_index(op.f('ix_claim_simulations_id'), table_name='claim_simulations')
    op.alter_column('claim_simulations', 'claim_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('claim_simulations', 'tindakan_sekunder_id')
    op.drop_column('claim_simulations', 'tindakan_utama_id')
    op.drop_column('claim_simulations', 'stage')
    op.drop_column('claim_diagnoses', 'struktur_icd10')
    op.add_column('claim_ai_recommendations', sa.Column('regulation_refs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
