"""add deskripsi_tindakan to claim_procedure_details

Revision ID: d22bc6652b7d
Revises: 3ef452367e33
Create Date: 2025-10-21 07:29:58.958294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd22bc6652b7d'
down_revision: Union[str, None] = '3ef452367e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_procedure_details', sa.Column('deskripsi_tindakan', sa.Text(), nullable=True))
    op.alter_column('claim_procedures', 'procedure_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim_procedures', 'procedure_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('claim_procedure_details', 'deskripsi_tindakan')
    # ### end Alembic commands ###
