"""make validitas_tindakan nullable from claim_procedure_details

Revision ID: ed5cb079e2d8
Revises: 4817ac29496c
Create Date: 2025-10-24 04:31:45.715248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed5cb079e2d8'
down_revision: Union[str, None] = '4817ac29496c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim_procedure_details', 'validitas_tindakan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim_procedure_details', 'validitas_tindakan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
