"""add icd9 fields to claim_procedure_details

Revision ID: 000674718b5b
Revises: 21f687a230d8
Create Date: 2025-09-17 14:30:27.368145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000674718b5b'
down_revision: Union[str, None] = '21f687a230d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim_ai_recommendations', 'nama_kategori',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('claim_procedure_details', sa.Column('icd9_tindakan', sa.String(), nullable=False))
    op.add_column('claim_procedure_details', sa.Column('icd9_deskripsi_tindakan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_procedure_details', 'icd9_deskripsi_tindakan')
    op.drop_column('claim_procedure_details', 'icd9_tindakan')
    op.alter_column('claim_ai_recommendations', 'nama_kategori',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
