"""update users table and update claims table

Revision ID: 002fd933ee93
Revises: e538a448681b
Create Date: 2025-08-28 01:56:57.695013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002fd933ee93'
down_revision: Union[str, None] = 'e538a448681b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('claims', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('claims', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('claims_created_by_fkey', 'claims', type_='foreignkey')
    op.drop_column('claims', 'created_by')
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('sip_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'doctor'::character varying"))
    op.create_foreign_key(None, 'users', 'hospitals', ['hospital_id'], ['id'])
    op.drop_column('users', 'password')
    op.drop_column('users', 'dokter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dokter_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column(
        'users',
        'role',
        existing_type=sa.VARCHAR(length=50),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
        existing_server_default=sa.text("'doctor'::character varying"))
    op.drop_column('users', 'hospital_id')
    op.drop_column('users', 'sip_number')
    op.drop_column('users', 'name')
    op.add_column('claims', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('claims_created_by_fkey', 'claims', 'users', ['created_by'], ['id'])
    op.alter_column('claims', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('claims', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('claims', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
