"""add claim_idrg table

Revision ID: 0d72c95f422e
Revises: 872a48dbb4da
Create Date: 2025-10-01 00:08:18.939279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d72c95f422e'
down_revision: Union[str, None] = '872a48dbb4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_idrg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=False),
    sa.Column('group_idrg', sa.String(length=50), nullable=True),
    sa.Column('severity_index', sa.String(length=50), nullable=True),
    sa.Column('checklist', sa.Text(), nullable=True),
    sa.Column('faktor_severity', sa.Text(), nullable=True),
    sa.Column('ungroupable_alert', sa.Text(), nullable=True),
    sa.Column('simulasi_tarif', sa.String(length=50), nullable=True),
    sa.Column('gap_analysis', sa.String(length=50), nullable=True),
    sa.Column('rekomendasi_ai', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_dummy', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_idrg_id'), 'claim_idrg', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_idrg_id'), table_name='claim_idrg')
    op.drop_table('claim_idrg')
    # ### end Alembic commands ###
