"""update users table and update claims table and update visits table and update patients table and update medical_records table and update hospitals table and update medical_record_logs table

Revision ID: 1717c0323625
Revises: ed94c77fe492
Create Date: 2025-08-28 11:17:34.560921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1717c0323625'
down_revision: Union[str, None] = 'ed94c77fe492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_record_logs', 'data_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_record_logs', 'data_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
