"""add claim_idrg_diagnosis & claim_idrg_summary

Revision ID: 1b0f397d2ee1
Revises: 0d72c95f422e
Create Date: 2025-10-01 01:02:49.430268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b0f397d2ee1'
down_revision: Union[str, None] = '0d72c95f422e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_idrg_diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('group_idrg', sa.String(length=50), nullable=True),
    sa.Column('severity_index', sa.String(length=50), nullable=True),
    sa.Column('checklist', sa.Text(), nullable=True),
    sa.Column('faktor_severity', sa.Text(), nullable=True),
    sa.Column('ungroupable_alert', sa.Text(), nullable=True),
    sa.Column('simulasi_tarif', sa.String(length=50), nullable=True),
    sa.Column('gap_analysis', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_dummy', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_idrg_diagnosis_id'), 'claim_idrg_diagnosis', ['id'], unique=False)
    op.create_table('claim_idrg_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('group_idrg_kombinasi', sa.String(length=50), nullable=True),
    sa.Column('severity_kombinasi', sa.String(length=50), nullable=True),
    sa.Column('checklist_kombinasi', sa.Text(), nullable=True),
    sa.Column('faktor_severity', sa.Text(), nullable=True),
    sa.Column('risiko_ungroupable', sa.Text(), nullable=True),
    sa.Column('estimasi_tarif', sa.String(length=50), nullable=True),
    sa.Column('gap_inacbg_vs_idrg', sa.String(length=50), nullable=True),
    sa.Column('rekomendasi_ai', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_dummy', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_idrg_summary_id'), 'claim_idrg_summary', ['id'], unique=False)
    op.drop_index('ix_claim_idrg_id', table_name='claim_idrg')
    op.drop_table('claim_idrg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_idrg',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('context', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('group_idrg', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('severity_index', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('checklist', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('faktor_severity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ungroupable_alert', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('simulasi_tarif', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gap_analysis', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rekomendasi_ai', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_dummy', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name='claim_idrg_claim_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='claim_idrg_pkey')
    )
    op.create_index('ix_claim_idrg_id', 'claim_idrg', ['id'], unique=False)
    op.drop_index(op.f('ix_claim_idrg_summary_id'), table_name='claim_idrg_summary')
    op.drop_table('claim_idrg_summary')
    op.drop_index(op.f('ix_claim_idrg_diagnosis_id'), table_name='claim_idrg_diagnosis')
    op.drop_table('claim_idrg_diagnosis')
    # ### end Alembic commands ###
