"""update claims table and update visits table

Revision ID: 2a17e72e1397
Revises: e62008ad2a63
Create Date: 2025-08-24 23:23:37.278674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a17e72e1397'
down_revision: Union[str, None] = 'e62008ad2a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'dokter',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('visits', 'dokter',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'dokter',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('claims', 'dokter',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
