"""add is_deleted and is_dummy to claims

Revision ID: 2bc6b2ba2467
Revises: 576fd6fdaa96
Create Date: 2025-09-07 17:20:38.770904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc6b2ba2467'
down_revision: Union[str, None] = '576fd6fdaa96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('claims', sa.Column('is_dummy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'is_dummy')
    op.drop_column('claims', 'is_deleted')
    # ### end Alembic commands ###
