"""drop subtype from claim_diagnoses

Revision ID: 2fca743298f1
Revises: 30eebcca003a
Create Date: 2025-09-25 02:21:55.042938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fca743298f1'
down_revision: Union[str, None] = '30eebcca003a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_diagnoses', 'subtype')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_diagnoses', sa.Column('subtype', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
