"""Refactor AIRecommendation models

Revision ID: 30eebcca003a
Revises: e61b1968c651
Create Date: 2025-09-24 14:52:44.708857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30eebcca003a'
down_revision: Union[str, None] = 'e61b1968c651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_ai_recommendations', 'tindakan')
    op.drop_column('claim_ai_recommendations', 'klinis')
    op.drop_column('claim_ai_recommendations', 'nama_kategori')
    op.drop_column('claim_ai_recommendations', 'icd10_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_ai_recommendations', sa.Column('icd10_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('claim_ai_recommendations', sa.Column('nama_kategori', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('claim_ai_recommendations', sa.Column('klinis', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('claim_ai_recommendations', sa.Column('tindakan', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
