"""drop diagnosis_id from claim_diagnosis_evaluations

Revision ID: 31f0ee65bbe1
Revises: 907d31c2210e
Create Date: 2025-09-28 02:07:48.316339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f0ee65bbe1'
down_revision: Union[str, None] = '907d31c2210e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
