"""update hospitals table

Revision ID: 36010e6e061d
Revises: 4c8326615311
Create Date: 2025-08-24 16:22:26.967382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36010e6e061d'
down_revision: Union[str, None] = '4c8326615311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('hospitals', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_foreign_key(None, 'hospitals', 'users', ['email'], ['email'])
    op.create_foreign_key(None, 'hospitals', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.drop_column('hospitals', 'email')
    op.drop_column('hospitals', 'user_id')
    # ### end Alembic commands ###
