"""update claims table

Revision ID: 3941da19e3a7
Revises: ba7bc83ba5a0
Create Date: 2025-08-26 15:08:09.284826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3941da19e3a7'
down_revision: Union[str, None] = 'ba7bc83ba5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('tanggal_claim', sa.Date(), nullable=True))
    op.alter_column('claims', 'tanggal_kunjungan',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'tanggal_kunjungan',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('claims', 'tanggal_claim')
    # ### end Alembic commands ###
