"""update users table and update claims table and update visits table and update patients table and update medical_records table and update hospitals table

Revision ID: 4954f981e7c6
Revises: 38b804c7e421
Create Date: 2025-08-28 03:30:12.181318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4954f981e7c6'
down_revision: Union[str, None] = '38b804c7e421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
