"""add visits table and update patients and update claims table

Revision ID: 4c8326615311
Revises: 6e9f6e9d6eb8
Create Date: 2025-08-24 16:17:06.156710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8326615311'
down_revision: Union[str, None] = '6e9f6e9d6eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('eksternal_visit_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('tanggal_kunjungan', sa.Date(), nullable=False),
    sa.Column('poli', sa.String(length=100), nullable=True),
    sa.Column('dokter', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eksternal_visit_id')
    )
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.add_column('claims', sa.Column('obat', sa.Text(), nullable=True))
    op.add_column('claims', sa.Column('hasil', sa.Text(), nullable=True))
    op.add_column('claims', sa.Column('visit_id', sa.Integer(), nullable=True))
    op.add_column('claims', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.add_column('claims', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'claims', 'visits', ['visit_id'], ['id'])
    op.create_foreign_key(None, 'claims', 'hospitals', ['hospital_id'], ['id'])
    op.add_column('patients', sa.Column('no_rm', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('jenis_kelamin', sa.String(length=10), nullable=True))
    op.add_column('patients', sa.Column('eksternal_id', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'patients', ['eksternal_id'])
    op.create_unique_constraint(None, 'patients', ['no_rm'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'created_at')
    op.drop_column('patients', 'source')
    op.drop_column('patients', 'eksternal_id')
    op.drop_column('patients', 'jenis_kelamin')
    op.drop_column('patients', 'no_rm')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_column('claims', 'created_at')
    op.drop_column('claims', 'hospital_id')
    op.drop_column('claims', 'visit_id')
    op.drop_column('claims', 'hasil')
    op.drop_column('claims', 'obat')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
