"""update visits table

Revision ID: 4f48a26aa3ff
Revises: 64f52ca4b97f
Create Date: 2025-08-25 01:50:18.661420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f48a26aa3ff'
down_revision: Union[str, None] = '64f52ca4b97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('visits', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('visits', 'tanggal_kunjungan',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'tanggal_kunjungan',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('visits', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visits', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
