"""add is_deleted and is_dummy to claims

Revision ID: 576fd6fdaa96
Revises: 210fb4c611ac
Create Date: 2025-09-07 17:19:12.143242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576fd6fdaa96'
down_revision: Union[str, None] = '210fb4c611ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
