"""add indikasi,lama_rawat,perpanjangan,kesesuaian_rs,syarat,kelayakan to claim_diagnoses and drop rawat_inap,faskes,rujukan from claim_diagnoses

Revision ID: 5775ea6affdc
Revises: ffc88e62098b
Create Date: 2025-09-25 10:54:59.127392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5775ea6affdc'
down_revision: Union[str, None] = 'ffc88e62098b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_diagnoses', sa.Column('indikasi', sa.Text(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('lama_rawat', sa.Text(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('perpanjangan', sa.Text(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('kesesuaian_rs', sa.Text(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('syarat', sa.Text(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('kelayakan', sa.Text(), nullable=True))
    op.drop_column('claim_diagnoses', 'rawat_inap')
    op.drop_column('claim_diagnoses', 'faskes')
    op.drop_column('claim_diagnoses', 'rujukan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_diagnoses', sa.Column('rujukan', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('claim_diagnoses', sa.Column('faskes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('claim_diagnoses', sa.Column('rawat_inap', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('claim_diagnoses', 'kelayakan')
    op.drop_column('claim_diagnoses', 'syarat')
    op.drop_column('claim_diagnoses', 'kesesuaian_rs')
    op.drop_column('claim_diagnoses', 'perpanjangan')
    op.drop_column('claim_diagnoses', 'lama_rawat')
    op.drop_column('claim_diagnoses', 'indikasi')
    # ### end Alembic commands ###
