"""extend claim_diagnoses and claim_procedures with modal detail fields

Revision ID: 5f1c85ef9548
Revises: 20e3b95c770a
Create Date: 2025-09-16 00:37:07.605022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f1c85ef9548'
down_revision: Union[str, None] = '20e3b95c770a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_claim_ai_recommendations_summary_id', table_name='claim_ai_recommendations_summary')
    op.drop_table('claim_ai_recommendations_summary')
    op.drop_column('claim_ai_recommendations', 'sim_detail')
    op.drop_column('claim_ai_recommendations', 'icd9_code')
    op.add_column('claim_diagnoses', sa.Column('justifikasi', sa.Text(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('syarat_klinis', sa.Text(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('bukti_klinis', sa.Text(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('kode_ganda', sa.String(length=50), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('z_code', sa.String(length=50), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('kode_bpjs_khusus', sa.String(length=50), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('rawat_inap', sa.Text(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('faskes', sa.Text(), nullable=True))
    op.add_column('claim_diagnoses', sa.Column('rujukan', sa.Text(), nullable=True))
    op.add_column('claim_procedures', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('claim_procedures', 'icd9_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_procedures', sa.Column('icd9_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('claim_procedures', 'description')
    op.drop_column('claim_diagnoses', 'rujukan')
    op.drop_column('claim_diagnoses', 'faskes')
    op.drop_column('claim_diagnoses', 'rawat_inap')
    op.drop_column('claim_diagnoses', 'kode_bpjs_khusus')
    op.drop_column('claim_diagnoses', 'z_code')
    op.drop_column('claim_diagnoses', 'kode_ganda')
    op.drop_column('claim_diagnoses', 'bukti_klinis')
    op.drop_column('claim_diagnoses', 'syarat_klinis')
    op.drop_column('claim_diagnoses', 'justifikasi')
    op.add_column('claim_ai_recommendations', sa.Column('icd9_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('claim_ai_recommendations', sa.Column('sim_detail', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('claim_ai_recommendations_summary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('medis', 'regulasi', 'tarif', name='recommendation_category'), autoincrement=False, nullable=False),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('valid', 'warning', 'invalid', name='recommendation_status'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_dummy', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name='claim_ai_recommendations_summary_claim_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='claim_ai_recommendations_summary_pkey')
    )
    op.create_index('ix_claim_ai_recommendations_summary_id', 'claim_ai_recommendations_summary', ['id'], unique=False)
    # ### end Alembic commands ###
