"""add validitas_detail fields to claim_procedure_evaluations and add validitas_detail fields to claim_diagnosis_evaluations

Revision ID: 61444ff21acd
Revises: 000674718b5b
Create Date: 2025-09-21 19:51:17.447568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61444ff21acd'
down_revision: Union[str, None] = '000674718b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_diagnosis_evaluations', sa.Column('validitas_detail', sa.String(length=255), nullable=True))
    op.add_column('claim_procedure_evaluations', sa.Column('validitas_detail', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_procedure_evaluations', 'validitas_detail')
    op.drop_column('claim_diagnosis_evaluations', 'validitas_detail')
    # ### end Alembic commands ###
