"""update users table and update claims table and update visits table and update patients table and update medical_records table and update hospitals table and update medical_record_logs table and update claim_logs table and update claim_ai_recommendations_summary table and update claim_ai_recommendations table and update claim_diagnoses table and update claim_procedures table and update claim_tariffs table

Revision ID: 63e12007387a
Revises: d7d0de3895de
Create Date: 2025-09-08 14:56:49.405032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e12007387a'
down_revision: Union[str, None] = 'd7d0de3895de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
