"""add hospitals and hospital_id to users & patients

Revision ID: 6e9f6e9d6eb8
Revises: 931d38fe7399
Create Date: 2025-08-21 13:40:13.111562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9f6e9d6eb8'
down_revision: Union[str, None] = '931d38fe7399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.add_column('patients', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'hospitals', ['hospital_id'], ['id'])
    op.add_column('users', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'hospitals', ['hospital_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'hospital_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'hospital_id')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
