"""add idrg_diagnosis_id and idrg_summary_id to claim_regulation_details

Revision ID: 7469890e7940
Revises: 1b0f397d2ee1
Create Date: 2025-10-02 02:01:42.553107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7469890e7940'
down_revision: Union[str, None] = '1b0f397d2ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_regulation_details', sa.Column('idrg_diagnosis_id', sa.Integer(), nullable=True))
    op.add_column('claim_regulation_details', sa.Column('idrg_summary_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'claim_regulation_details', 'claim_idrg_summary', ['idrg_summary_id'], ['id'])
    op.create_foreign_key(None, 'claim_regulation_details', 'claim_idrg_diagnosis', ['idrg_diagnosis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claim_regulation_details', type_='foreignkey')
    op.drop_constraint(None, 'claim_regulation_details', type_='foreignkey')
    op.drop_column('claim_regulation_details', 'idrg_summary_id')
    op.drop_column('claim_regulation_details', 'idrg_diagnosis_id')
    # ### end Alembic commands ###
