"""drop notes from claim_combination_alternatives

Revision ID: 74965337a9d3
Revises: 7947b4f889fd
Create Date: 2025-09-27 12:08:14.538258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74965337a9d3'
down_revision: Union[str, None] = '7947b4f889fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_combination_alternatives', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_combination_alternatives', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
