"""update visits table

Revision ID: 75f09ed42710
Revises: d8909888e533
Create Date: 2025-08-25 02:01:21.983544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f09ed42710'
down_revision: Union[str, None] = 'd8909888e533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('visits_eksternal_id_key', 'visits', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('visits_eksternal_id_key', 'visits', ['eksternal_id'])
    # ### end Alembic commands ###
