"""add claim_regulation_details table

Revision ID: 7947b4f889fd
Revises: 7ea1c2973015
Create Date: 2025-09-27 02:20:31.805360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7947b4f889fd'
down_revision: Union[str, None] = '7ea1c2973015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_regulation_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_id', sa.Integer(), nullable=True),
    sa.Column('procedure_id', sa.Integer(), nullable=True),
    sa.Column('judul_regulasi', sa.String(length=255), nullable=False),
    sa.Column('dasar_hukum', sa.String(length=255), nullable=True),
    sa.Column('bab_pasal', sa.String(length=255), nullable=True),
    sa.Column('isi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_dummy', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['claim_diagnoses.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['claim_procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_regulation_details_id'), 'claim_regulation_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_regulation_details_id'), table_name='claim_regulation_details')
    op.drop_table('claim_regulation_details')
    # ### end Alembic commands ###
