"""update hospitals and update users table

Revision ID: 7ad001e3c2af
Revises: 36010e6e061d
Create Date: 2025-08-24 16:40:34.676955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad001e3c2af'
down_revision: Union[str, None] = '36010e6e061d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.drop_constraint('hospitals_user_id_fkey', 'hospitals', type_='foreignkey')
    op.drop_constraint('hospitals_email_fkey', 'hospitals', type_='foreignkey')
    op.create_foreign_key(None, 'hospitals', 'users', ['admin_id'], ['id'])
    op.drop_column('hospitals', 'email')
    op.drop_column('hospitals', 'user_id')
    op.drop_constraint('users_hospital_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'hospital_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_hospital_id_fkey', 'users', 'hospitals', ['hospital_id'], ['id'])
    op.add_column('hospitals', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hospitals', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hospitals', type_='foreignkey')
    op.create_foreign_key('hospitals_email_fkey', 'hospitals', 'users', ['email'], ['email'])
    op.create_foreign_key('hospitals_user_id_fkey', 'hospitals', 'users', ['user_id'], ['id'])
    op.drop_column('hospitals', 'admin_id')
    # ### end Alembic commands ###
