"""add tindakan and child to claim_ai_recommendations

Revision ID: 80d6970c8ee5
Revises: 8234a0b243d3
Create Date: 2025-09-16 15:15:08.383376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80d6970c8ee5'
down_revision: Union[str, None] = '8234a0b243d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_ai_recommendations', sa.Column('klinis', sa.Text(), nullable=True))
    op.add_column('claim_ai_recommendations', sa.Column('tindakan', sa.Text(), nullable=True))
    op.add_column('claim_ai_recommendations', sa.Column('child', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('claim_ai_recommendations', 'sim_text')
    op.drop_column('claims', 'simulasi_draft')
    op.drop_column('claims', 'summary_draft')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('summary_draft', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('simulasi_draft', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('claim_ai_recommendations', sa.Column('sim_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('claim_ai_recommendations', 'child')
    op.drop_column('claim_ai_recommendations', 'tindakan')
    op.drop_column('claim_ai_recommendations', 'klinis')
    # ### end Alembic commands ###
