"""add claim_procedure_details table

Revision ID: 8234a0b243d3
Revises: c6308307e5ae
Create Date: 2025-09-16 11:15:49.958890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8234a0b243d3'
down_revision: Union[str, None] = 'c6308307e5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_procedure_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_simulation_id', sa.Integer(), nullable=True),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('validitas_tindakan', sa.String(), nullable=False),
    sa.Column('status_tindakan', sa.String(), nullable=True),
    sa.Column('ina_cbg_tindakan', sa.Text(), nullable=True),
    sa.Column('faskes_tindakan', sa.Text(), nullable=True),
    sa.Column('rawat_inap_tindakan', sa.Text(), nullable=True),
    sa.Column('syarat_klinis_tindakan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_dummy', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['claim_simulation_id'], ['claim_simulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['procedure_id'], ['claim_procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_procedure_details_id'), 'claim_procedure_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_procedure_details_id'), table_name='claim_procedure_details')
    op.drop_table('claim_procedure_details')
    # ### end Alembic commands ###
