"""rename td to tekanan_darah

Revision ID: 8795f7c3b5f5
Revises: 61444ff21acd
Create Date: 2025-09-22 15:33:46.305465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8795f7c3b5f5'
down_revision: Union[str, None] = '61444ff21acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('tekanan_darah', sa.String(length=100), nullable=True))
    op.drop_column('medical_records', 'td')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('td', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('medical_records', 'tekanan_darah')
    # ### end Alembic commands ###
