"""update claims table

Revision ID: 88c41b75f711
Revises: fd271b7ee908
Create Date: 2025-09-04 01:24:40.313268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c41b75f711'
down_revision: Union[str, None] = 'fd271b7ee908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'claim_ai_recommendations', 'claims', ['claim_id'], ['id'])
    op.create_foreign_key(None, 'claim_diagnoses', 'claims', ['claim_id'], ['id'])
    op.create_foreign_key(None, 'claim_logs', 'claims', ['claim_id'], ['id'])
    op.create_foreign_key(None, 'claim_procedures', 'claims', ['claim_id'], ['id'])
    op.create_foreign_key(None, 'claim_tariffs', 'claims', ['claim_id'], ['id'])
    op.add_column('claims', sa.Column('simulasi_draft', sa.JSON(), nullable=True))
    op.add_column('claims', sa.Column('summary_draft', sa.JSON(), nullable=True))
    op.add_column('claims', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('medical_record_logs', 'medical_record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('medical_record_logs', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'medical_record_logs', 'medical_records', ['medical_record_id'], ['id'])
    op.add_column('medical_records', sa.Column('record_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'record_type')
    op.drop_constraint(None, 'medical_record_logs', type_='foreignkey')
    op.alter_column('medical_record_logs', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('medical_record_logs', 'medical_record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('claims', 'status')
    op.drop_column('claims', 'summary_draft')
    op.drop_column('claims', 'simulasi_draft')
    op.drop_constraint(None, 'claim_tariffs', type_='foreignkey')
    op.drop_constraint(None, 'claim_procedures', type_='foreignkey')
    op.drop_constraint(None, 'claim_logs', type_='foreignkey')
    op.drop_constraint(None, 'claim_diagnoses', type_='foreignkey')
    op.drop_constraint(None, 'claim_ai_recommendations', type_='foreignkey')
    # ### end Alembic commands ###
