"""update patients table and update users table and update hospitals table

Revision ID: 8b6b2dcfa663
Revises: 75f09ed42710
Create Date: 2025-08-26 11:25:26.070045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6b2dcfa663'
down_revision: Union[str, None] = '75f09ed42710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('kode_hospital', sa.String(length=20), nullable=True))
    op.add_column('hospitals', sa.Column('tipe_hospital', sa.String(length=50), nullable=True))
    op.add_column('hospitals', sa.Column('jenis_hospital', sa.String(length=50), nullable=True))
    op.add_column('hospitals', sa.Column('telepon', sa.String(length=20), nullable=True))
    op.add_column('hospitals', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('hospitals', sa.Column('status_akreditasi', sa.String(length=50), nullable=True))
    op.add_column('hospitals', sa.Column('status_bridging', sa.String(length=50), nullable=True))
    op.add_column('hospitals', sa.Column('jumlah_tempat_tidur', sa.Integer(), nullable=True))
    op.alter_column('hospitals', 'nama',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.create_unique_constraint(None, 'hospitals', ['email'])
    op.create_unique_constraint(None, 'hospitals', ['kode_hospital'])
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('jabatan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dokter_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dokter_id')
    op.drop_column('users', 'jabatan')
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'hospitals', type_='unique')
    op.drop_constraint(None, 'hospitals', type_='unique')
    op.alter_column('hospitals', 'nama',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('hospitals', 'jumlah_tempat_tidur')
    op.drop_column('hospitals', 'status_bridging')
    op.drop_column('hospitals', 'status_akreditasi')
    op.drop_column('hospitals', 'email')
    op.drop_column('hospitals', 'telepon')
    op.drop_column('hospitals', 'jenis_hospital')
    op.drop_column('hospitals', 'tipe_hospital')
    op.drop_column('hospitals', 'kode_hospital')
    # ### end Alembic commands ###
