"""drop procedure_id from claim_procedure_evaluations

Revision ID: 907d31c2210e
Revises: 74965337a9d3
Create Date: 2025-09-28 02:07:19.794117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907d31c2210e'
down_revision: Union[str, None] = '74965337a9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('claim_diagnosis_evaluations_diagnosis_id_fkey', 'claim_diagnosis_evaluations', type_='foreignkey')
    op.drop_column('claim_diagnosis_evaluations', 'diagnosis_id')
    op.drop_constraint('claim_procedure_evaluations_procedure_id_fkey', 'claim_procedure_evaluations', type_='foreignkey')
    op.drop_column('claim_procedure_evaluations', 'procedure_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_procedure_evaluations', sa.Column('procedure_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('claim_procedure_evaluations_procedure_id_fkey', 'claim_procedure_evaluations', 'claim_procedures', ['procedure_id'], ['id'])
    op.add_column('claim_diagnosis_evaluations', sa.Column('diagnosis_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('claim_diagnosis_evaluations_diagnosis_id_fkey', 'claim_diagnosis_evaluations', 'claim_diagnoses', ['diagnosis_id'], ['id'])
    # ### end Alembic commands ###
