"""add claims table and update patients

Revision ID: 931d38fe7399
Revises: 
Create Date: 2025-08-21 12:41:42.474995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931d38fe7399'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal_kunjungan', sa.Date(), nullable=False),
    sa.Column('dokter', sa.String(length=100), nullable=False),
    sa.Column('diagnosis_awal', sa.Text(), nullable=True),
    sa.Column('kode_icd', sa.String(length=20), nullable=True),
    sa.Column('tindakan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.add_column('patients', sa.Column('alamat', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('patients', sa.Column('no_hp', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_unique_constraint(None, 'patients', ['email'])
    op.drop_column('patients', 'diagnosis')
    op.drop_column('patients', 'tindakan')
    op.drop_column('patients', 'dokter')
    op.drop_column('patients', 'tanggal_kunjungan')
    op.drop_constraint('users_auth0_sub_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_auth0_sub'), 'users', ['auth0_sub'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_auth0_sub'), table_name='users')
    op.create_unique_constraint('users_auth0_sub_key', 'users', ['auth0_sub'])
    op.add_column('patients', sa.Column('tanggal_kunjungan', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('dokter', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('tindakan', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('diagnosis', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_column('patients', 'no_hp')
    op.drop_column('patients', 'email')
    op.drop_column('patients', 'alamat')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
