"""update patients table and update users table and update hospitals table

Revision ID: ae5cb9fe1303
Revises: 8b6b2dcfa663
Create Date: 2025-08-26 11:25:57.359893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5cb9fe1303'
down_revision: Union[str, None] = '8b6b2dcfa663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('no_ktp', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('no_bpjs', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'patients', ['no_ktp'])
    op.create_unique_constraint(None, 'patients', ['no_bpjs'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'no_bpjs')
    op.drop_column('patients', 'no_ktp')
    # ### end Alembic commands ###
