"""update claims table

Revision ID: b25c60a7dd0b
Revises: 3941da19e3a7
Create Date: 2025-08-26 22:49:42.752630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25c60a7dd0b'
down_revision: Union[str, None] = '3941da19e3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
