"""update visits table

Revision ID: ba7bc83ba5a0
Revises: ae5cb9fe1303
Create Date: 2025-08-26 11:28:48.045823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7bc83ba5a0'
down_revision: Union[str, None] = 'ae5cb9fe1303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('jenis_kunjungan', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'jenis_kunjungan')
    # ### end Alembic commands ###
