"""update users table and update claims table and update visits table and update patients table and update medical_records table and update hospitals table

Revision ID: cf094f0661dc
Revises: 002fd933ee93
Create Date: 2025-08-28 03:12:51.383514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf094f0661dc'
down_revision: Union[str, None] = '002fd933ee93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('claims', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'doctor'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'doctor'::character varying"))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('claims', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('claims', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
