"""add is_deleted and is_dummy flag

Revision ID: d218e18f9763
Revises: 2bc6b2ba2467
Create Date: 2025-09-07 21:29:12.332747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd218e18f9763'
down_revision: Union[str, None] = '2bc6b2ba2467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
