"""update users table and update claims table and update visits table and update patients table and update medical_records table and update hospitals table and update medical_record_logs table

Revision ID: d2f2fa03a303
Revises: 1717c0323625
Create Date: 2025-08-29 13:41:39.005999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f2fa03a303'
down_revision: Union[str, None] = '1717c0323625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
