"""update visits table

Revision ID: d68355f0096b
Revises: 4f48a26aa3ff
Create Date: 2025-08-25 01:52:26.629881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68355f0096b'
down_revision: Union[str, None] = '4f48a26aa3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('eksternal_id', sa.String(length=100), nullable=True))
    op.drop_constraint('visits_eksternal_visit_id_key', 'visits', type_='unique')
    op.create_unique_constraint(None, 'visits', ['eksternal_id'])
    op.drop_column('visits', 'eksternal_visit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('eksternal_visit_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'visits', type_='unique')
    op.create_unique_constraint('visits_eksternal_visit_id_key', 'visits', ['eksternal_visit_id'])
    op.drop_column('visits', 'eksternal_id')
    # ### end Alembic commands ###
