"""update users table and update claims table and update visits table and update patients table and update medical_records table and update hospitals table and update medical_record_logs table and update claim_logs table and update claim_ai_recommendations_summary table and update claim_ai_recommendations table and update claim_diagnoses table and update claim_procedures table and update claim_tariffs table

Revision ID: d7d0de3895de
Revises: 7a5787bc54e0
Create Date: 2025-09-08 14:15:18.247697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7d0de3895de'
down_revision: Union[str, None] = '7a5787bc54e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_ai_recommendations',
        sa.Column('sim_text', sa.Text(), nullable=True)
    )

    # Step 2: isi data lama biar ga NULL
    op.execute("UPDATE claim_ai_recommendations SET sim_text = '' WHERE sim_text IS NULL")

    # Step 3: baru alter jadi not null
    op.alter_column('claim_ai_recommendations', 'sim_text', nullable=False)
    op.alter_column('claim_ai_recommendations', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('claim_ai_recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('claim_ai_recommendations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('claim_ai_recommendations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_ai_recommendations', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('claim_ai_recommendations', 'text')
    op.add_column('claim_ai_recommendations_summary', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('claim_ai_recommendations_summary', 'category',
               existing_type=postgresql.ENUM('medis', 'regulasi', 'tarif', name='recommendation_category'),
               nullable=False)
    op.alter_column('claim_ai_recommendations_summary', 'status',
               existing_type=postgresql.ENUM('valid', 'warning', 'invalid', name='recommendation_status'),
               nullable=False)
    op.alter_column('claim_ai_recommendations_summary', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('claim_ai_recommendations_summary', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_ai_recommendations_summary', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_diagnoses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('claim_diagnoses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('claim_diagnoses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_diagnoses', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_logs', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_procedures', 'requirement_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_procedures', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('claim_procedures', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('claim_procedures', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_procedures', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_tariffs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('claim_tariffs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('claim_tariffs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claim_tariffs', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('claims', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('claims', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claims', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claims', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claims', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('claims', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('hospitals', 'nama',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('hospitals', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('hospitals', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medical_record_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('medical_record_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medical_record_logs', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('medical_records', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # Step 2: isi data lama biar ga NULL
    op.execute("UPDATE medical_records SET record_type = '' WHERE record_type IS NULL")
    op.alter_column('medical_records', 'record_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('medical_records', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medical_records', 'notes_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('medical_records', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('medical_records', 'doctor_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('medical_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('medical_records', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('medical_records', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('patients', 'nama',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.execute("UPDATE patients SET created_at = '2024-01-01 00:00:00' WHERE created_at IS NULL")
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('patients', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('patients', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('visits', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('visits', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.execute("UPDATE visits SET hospital_id = 1, tanggal_kunjungan = '2024-01-01', created_at = '2024-01-01 00:00:00' WHERE hospital_id IS NULL")
    op.alter_column('visits', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visits', 'tanggal_kunjungan',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('visits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('visits', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('visits', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('visits', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('visits', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('visits', 'tanggal_kunjungan',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('visits', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('visits', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('visits', 'updated_at')
    op.alter_column('users', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('patients', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('patients', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('patients', 'nama',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('patients', 'updated_at')
    op.alter_column('medical_records', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medical_records', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medical_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('medical_records', 'doctor_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('medical_records', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('medical_records', 'notes_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('medical_records', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medical_records', 'record_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('medical_records', 'updated_at')
    op.alter_column('medical_record_logs', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medical_record_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('medical_record_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('hospitals', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hospitals', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hospitals', 'nama',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('claims', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('claims', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claims', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claims', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claims', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('claims', 'updated_at')
    op.alter_column('claim_tariffs', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_tariffs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_tariffs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('claim_tariffs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('claim_procedures', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_procedures', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_procedures', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('claim_procedures', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('claim_procedures', 'requirement_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_logs', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_diagnoses', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_diagnoses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_diagnoses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('claim_diagnoses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('claim_ai_recommendations_summary', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_ai_recommendations_summary', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_ai_recommendations_summary', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('claim_ai_recommendations_summary', 'status',
               existing_type=postgresql.ENUM('valid', 'warning', 'invalid', name='recommendation_status'),
               nullable=True)
    op.alter_column('claim_ai_recommendations_summary', 'category',
               existing_type=postgresql.ENUM('medis', 'regulasi', 'tarif', name='recommendation_category'),
               nullable=True)
    op.drop_column('claim_ai_recommendations_summary', 'updated_at')
    op.add_column('claim_ai_recommendations', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('claim_ai_recommendations', 'is_dummy',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_ai_recommendations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('claim_ai_recommendations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('claim_ai_recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('claim_ai_recommendations', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('claim_ai_recommendations', 'sim_text')
    # ### end Alembic commands ###
