"""update visits table

Revision ID: d8909888e533
Revises: 8730bb630040
Create Date: 2025-08-25 01:55:08.578517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8909888e533'
down_revision: Union[str, None] = '8730bb630040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('sumber', sa.String(length=100), nullable=True))
    op.drop_column('visits', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('visits', 'sumber')
    # ### end Alembic commands ###
