"""add updated_at to claim_combination_alternatives and add updated_at to claim_diagnosis_evaluations

Revision ID: e40071d18111
Revises: ef50f8479f8f
Create Date: 2025-09-23 01:54:16.617899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40071d18111'
down_revision: Union[str, None] = 'ef50f8479f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_combination_alternatives', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('claim_diagnosis_evaluations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('claim_procedure_evaluations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_procedure_evaluations', 'updated_at')
    op.drop_column('claim_diagnosis_evaluations', 'updated_at')
    op.drop_column('claim_combination_alternatives', 'updated_at')
    # ### end Alembic commands ###
