"""update visits table and update claims table and add MedicalRecords table

Revision ID: e538a448681b
Revises: b25c60a7dd0b
Create Date: 2025-08-28 01:04:34.558771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e538a448681b'
down_revision: Union[str, None] = 'b25c60a7dd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('notes_date', sa.Date(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('doctor_name', sa.String(length=100), nullable=True),
    sa.Column('riwayat_penyakit', sa.Text(), nullable=True),
    sa.Column('riwayat_pengobatan', sa.Text(), nullable=True),
    sa.Column('riwayat_operasi', sa.Text(), nullable=True),
    sa.Column('alergi', sa.Text(), nullable=True),
    sa.Column('keluhan', sa.Text(), nullable=True),
    sa.Column('gejala_lain', sa.Text(), nullable=True),
    sa.Column('td', sa.String(length=100), nullable=True),
    sa.Column('nadi', sa.String(length=100), nullable=True),
    sa.Column('pernapasan', sa.String(length=100), nullable=True),
    sa.Column('suhu', sa.String(length=100), nullable=True),
    sa.Column('spo2', sa.String(length=100), nullable=True),
    sa.Column('berat_badan', sa.String(length=100), nullable=True),
    sa.Column('tinggi_badan', sa.String(length=100), nullable=True),
    sa.Column('hemoglobin', sa.String(length=100), nullable=True),
    sa.Column('leukosit', sa.String(length=100), nullable=True),
    sa.Column('trombosit', sa.String(length=100), nullable=True),
    sa.Column('gula_darah', sa.String(length=100), nullable=True),
    sa.Column('creatinin', sa.String(length=100), nullable=True),
    sa.Column('rontgen_thorax', sa.Text(), nullable=True),
    sa.Column('ct_scan', sa.Text(), nullable=True),
    sa.Column('usg', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis_awal', sa.Text(), nullable=True),
    sa.Column('komorbid', sa.Text(), nullable=True),
    sa.Column('komplikasi', sa.Text(), nullable=True),
    sa.Column('diagnosis_akhir', sa.Text(), nullable=True),
    sa.Column('tindakan', sa.Text(), nullable=True),
    sa.Column('obat', sa.Text(), nullable=True),
    sa.Column('validasi_fornas', sa.Text(), nullable=True),
    sa.Column('notes_doctor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_id'), 'medical_records', ['id'], unique=False)
    op.add_column('claims', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.add_column('claims', sa.Column('doctor_name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'claims', 'users', ['doctor_id'], ['id'])
    op.drop_column('claims', 'dokter')
    op.add_column('visits', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.add_column('visits', sa.Column('doctor_name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'visits', 'users', ['doctor_id'], ['id'])
    op.drop_column('visits', 'dokter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('dokter', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_column('visits', 'doctor_name')
    op.drop_column('visits', 'doctor_id')
    op.add_column('claims', sa.Column('dokter', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_column('claims', 'doctor_name')
    op.drop_column('claims', 'doctor_id')
    op.drop_index(op.f('ix_medical_records_id'), table_name='medical_records')
    op.drop_table('medical_records')
    # ### end Alembic commands ###
