"""drop description from claim_procedures & set claim_simulation_id not null

Revision ID: e61b1968c651
Revises: e40071d18111
Create Date: 2025-09-24 10:26:12.799142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61b1968c651'
down_revision: Union[str, None] = 'e40071d18111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim_procedure_details', 'claim_simulation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim_procedure_details', 'claim_simulation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
