"""add diagnosis_id and procedure_id to claim_ai_recommendations

Revision ID: ef50f8479f8f
Revises: 8795f7c3b5f5
Create Date: 2025-09-23 01:38:22.151364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef50f8479f8f'
down_revision: Union[str, None] = '8795f7c3b5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_ai_recommendations', sa.Column('diagnosis_id', sa.Integer(), nullable=True))
    op.add_column('claim_ai_recommendations', sa.Column('procedure_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'claim_ai_recommendations', 'claim_diagnoses', ['diagnosis_id'], ['id'])
    op.create_foreign_key(None, 'claim_ai_recommendations', 'claim_procedures', ['procedure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claim_ai_recommendations', type_='foreignkey')
    op.drop_constraint(None, 'claim_ai_recommendations', type_='foreignkey')
    op.drop_column('claim_ai_recommendations', 'procedure_id')
    op.drop_column('claim_ai_recommendations', 'diagnosis_id')
    # ### end Alembic commands ###
