"""drop icd9_deskripsi_tindakan from claim_procedure_details

Revision ID: ffc88e62098b
Revises: 2fca743298f1
Create Date: 2025-09-25 03:02:49.585657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc88e62098b'
down_revision: Union[str, None] = '2fca743298f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_procedure_details', 'icd9_deskripsi_tindakan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_procedure_details', sa.Column('icd9_deskripsi_tindakan', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
