"""Initial migration for data hub tables

Revision ID: 0d43dd9516f1
Revises: 
Create Date: 2025-10-25 10:03:22.295726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d43dd9516f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_hub_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_hub_logs_record_id'), 'data_hub_logs', ['record_id'], unique=False)
    op.create_table('data_hub_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('uploader', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_hub_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=True),
    sa.Column('hospital_id', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('json_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_hub_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_hub_records_hospital_id'), 'data_hub_records', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_data_hub_records_record_id'), 'data_hub_records', ['record_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_hub_records_record_id'), table_name='data_hub_records')
    op.drop_index(op.f('ix_data_hub_records_hospital_id'), table_name='data_hub_records')
    op.drop_table('data_hub_records')
    op.drop_table('data_hub_sources')
    op.drop_index(op.f('ix_data_hub_logs_record_id'), table_name='data_hub_logs')
    op.drop_table('data_hub_logs')
    # ### end Alembic commands ###
